### ISSUE TITLE
More detailed instruction on compilation

### ISSUE THREAD

**Issue by bnn1** [BFrizzleFoShizzle/RE_Kenshi#1]
Hello. Could you please provide more detailed instruction on compiling this program? 
trying to compile this on linux and kinda lost 😂
Or maybe add built files?

**Comment by BFrizzleFoShizzle** [comment]
The code only works with Microsoft's Visual C++ compiler, so you probably can't easily compile it on linux unless you manage to set that up through Wine or similar. The code is extremely sensitive to compiler versions as it links to statically-compiled code in Kenshi, so it only works with the MSVC++ compiler version bundled in the Windows SDK v7.1, as this is roughly what Kenshi used.
If you're running Kenshi through Proton or Wine, you should be able to compile the .dll on windows, copy it over and install the mod manually (the automated installer I wrote doesn't work properly on linux). I've tested this on Mint before and can confirm it works.
You can find prebuilt releases here: https://github.com/BFrizzleFoShizzle/RE_Kenshi/releases
or here: https://www.nexusmods.com/kenshi/mods/847

**Comment by bnn1** [comment]
By built files I meant the dll and ini that your program produces. I tried running ur program on windows 8.1 x86 but it says OS is not supported. Could you please upload dll and ini file?

**Comment by sTiKyt** [comment]
> The code only works with Microsoft's Visual C++ compiler, so you probably can't easily compile it on linux unless you manage to set that up through Wine or similar. The code is extremely sensitive to compiler versions as it links to statically-compiled code in Kenshi, so it only works with the MSVC++ compiler version bundled in the Windows SDK v7.1, as this is roughly what Kenshi used. If you're running Kenshi through Proton or Wine, you should be able to compile the .dll on windows, copy it over and install the mod manually (the automated installer I wrote doesn't work properly on linux). I've tested this on Mint before and can confirm it works. You can find prebuilt releases here: https://github.com/BFrizzleFoShizzle/RE_Kenshi/releases or here: https://www.nexusmods.com/kenshi/mods/847

But there are no prebuilt files, and only an installer?

**Comment by BFrizzleFoShizzle** [comment]
@sTiKyt all the files needed to manually install are in the `tools/` folder of the installer. 
You can look here https://github.com/BFrizzleFoShizzle/RE_Kenshi/issues/4 to find the last writeup I did on how to manually install. It might be out of date, but I also don't officially support Linux, so as of right now I don't plan on actively maintaining that guide.
