### ISSUE TITLE
Hash does not match. This mod is only compatible with kenshi 1.51,1.55,1.59

### ISSUE THREAD

**Issue by bnn1** [BFrizzleFoShizzle/RE_Kenshi#2]
Steam version of Kenshi 1.59

![image](https://user-images.githubusercontent.com/55663639/153023947-a867d385-5e3f-4f5d-a971-736a136b939f.png)
![image](https://user-images.githubusercontent.com/55663639/153024146-2df83d91-5d94-4e9f-bf46-48c3f11de259.png)

**Comment by BFrizzleFoShizzle** [comment]
Dang, looks like this is a bug in the installer, I've tracked it down and should have a fix shortly

**Comment by BFrizzleFoShizzle** [comment]
Thanks for the heads up - I've updated the v0.2.3 release with the fix: https://github.com/BFrizzleFoShizzle/RE_Kenshi/releases/tag/v0.2.3
I'll also update the files on Nexus, it usually takes 24hrs for them to get approved.
