### ISSUE TITLE
Hash mismatch for df4a5a (Kenshi 1.0.65 + FCS 2.14.2 hotfix) 

### ISSUE THREAD

**Issue by Lightsockie** [BFrizzleFoShizzle/RE_Kenshi#5]
All there in the title, just need to pin the new version I'm guessin'? I'm installing via Proton/Wine, but I don't think that's gonna matter here (same exe either way)

**Comment by BFrizzleFoShizzle** [comment]
Yep, I'm working on this as we speak. With any luck I'll have a version in testing on the GMG discord by the end of the day, followed by a release here + on Nexus a couple days after.

**Comment by Lightsockie** [comment]
Hero! Godspeed dev! 

First day of heavily modding my Kenshi. Kinda funny how a day later or sooner I wouldn't have even noticed lol

**Comment by BFrizzleFoShizzle** [comment]
The new release is out now
